application: shashinhenge
version: 1
runtime: python
api_version: 1


builtins:
- remote_api: on
- datastore_admin: on

inbound_services:
- warmup


handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /.*
  script:  djangoappengine/main/main.py
  
